name: Zap MFA

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "export ZAP_USERNAME=$ZAP_USERNAME" >> $GITHUB_ENV
          echo "export ZAP_PASSWORD=$ZAP_PASSWORD" >> $GITHUB_ENV

      - name: Browser
        run: |
          wget https://ftp.mozilla.org/pub/firefox/releases/120.0.1/linux-x86_64/en-US/firefox-120.0.1.tar.bz2
          tar xjf firefox-120.0.1.tar.bz2
          sudo rm -rf /opt/firefox
          sudo mv firefox /opt/firefox120.0.1
          sudo ln -sf /opt/firefox120.0.1/firefox /usr/bin/firefox

      - name: Run Python
        run: |
          pip install selenium
          pip install pyotp==2.0.1
          python ./main.py   

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          docker_name: 'ictu/zap2docker-weekly'
          target: 'https://saint-gobain-uk--perftestin.sandbox.my.salesforce.com/'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: >
            --hook=/zap/auth_hook.py 
            -z "auth.loginurl=https://saint-gobain-uk--perftestin.sandbox.my.salesforce.com/
            auth.username=gomathy.gopinath@qualitestgroup.com.perftestin 
            auth.password=Password@3101
            auth.username_field=username
            auth.password_field=password 
            auth.submit_field=Login"
    
        
