name: Zap MFA

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Browser
        run: |
          wget https://ftp.mozilla.org/pub/firefox/releases/120.0.1/linux-x86_64/en-US/firefox-120.0.1.tar.bz2
          tar xjf firefox-120.0.1.tar.bz2
          sudo rm -rf /opt/firefox
          sudo mv firefox /opt/firefox120.0.1
          sudo ln -sf /opt/firefox120.0.1/firefox /usr/bin/firefox

      - name: Run Python
        run: |
          pip install selenium
          pip install pyotp==2.0.1
          python ./main.py   

      - name: Run Zap Scan
        run: |
         docker run -t owasp/zap2docker-weekly zap-api-scan.py -t \
         https://sguk-test-c3p-orchestration-imp-v1.de-c1.eu1.cloudhub.io/api/v1/accounts -f openapi 
